### ISSUE TITLE
Getting a key error in models.py

### ISSUE THREAD

**Issue by Aaditree** [hindbr/HINDbr#1]
File "models.py", line 124, in <module>
    hin_node_id = hin_node_dict[str(row[hin])][0]
KeyError: '1786'

**Comment by hindbr** [comment]
> File "models.py", line 124, in
> hin_node_id = hin_node_dict[str(row[hin])][0]
> KeyError: '1786'

Hi Aaditree, could you please describe your problem in more detail? For example, which project do you perform for the training?
